name: Build and Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm ci
          gulp
          rm -rf node_modules

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: reggionick/s3-deploy@v3
        with:
          folder: .
          bucket: hans-knecht-resume
          bucket-region: us-east-1
          dist-id: E2FX991HLNLYID
          invalidation: /
          private: true
          # filesToInclude: "css/* files/* img/* js/* index.html favicon.ico scss/* vendor/*"
